/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author admin
 */
public class Calculator extends javax.swing.JFrame implements operations{

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    public void disable1()
    {
        outputScreen.setEnabled(false);
        labelScreen.setEnabled(false);
        oneButton.setEnabled(false);
        twoButton.setEnabled(false);
        threeButton.setEnabled(false);
        fourButton.setEnabled(false);
        fiveButton.setEnabled(false);
        sixButton.setEnabled(false);
        sevenButton.setEnabled(false);
        eightButton.setEnabled(false);
        nineButton.setEnabled(false);
        zeroButton.setEnabled(false);
        cButton.setEnabled(false);
        plusButton.setEnabled(false);
        percentageButton.setEnabled(false);
        sqrtButton.setEnabled(false);
        backspaceButton.setEnabled(false);
        oneByXButton.setEnabled(false);
        x2Button.setEnabled(false);
        divideButton.setEnabled(false);
        multiplyButton.setEnabled(false);
        minusButton.setEnabled(false);
        equalButton.setEnabled(false);
        plusButton.setEnabled(false);
        dotButton.setEnabled(false);
        
    }

    public void enable1()
    {
        outputScreen.setEnabled(true);
        labelScreen.setEnabled(true);
        oneButton.setEnabled(true);
        twoButton.setEnabled(true);
        threeButton.setEnabled(true);
        fourButton.setEnabled(true);
        fiveButton.setEnabled(true);
        sixButton.setEnabled(true);
        sevenButton.setEnabled(true);
        eightButton.setEnabled(true);
        nineButton.setEnabled(true);
        zeroButton.setEnabled(true);
        cButton.setEnabled(true);
        plusButton.setEnabled(true);
        percentageButton.setEnabled(true);
        sqrtButton.setEnabled(true);
        backspaceButton.setEnabled(true);
        oneByXButton.setEnabled(true);
        x2Button.setEnabled(true);
        divideButton.setEnabled(true);
        multiplyButton.setEnabled(true);
        minusButton.setEnabled(true);
        equalButton.setEnabled(true);
        plusButton.setEnabled(true);
        dotButton.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sqrtButton = new javax.swing.JButton();
        percentageButton = new javax.swing.JButton();
        x2Button = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        onOffButton = new javax.swing.JButton();
        backspaceButton = new javax.swing.JButton();
        oneByXButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        dotButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();
        outputScreen = new javax.swing.JTextField();
        labelScreen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        sqrtButton.setBackground(new java.awt.Color(255, 255, 255));
        sqrtButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        sqrtButton.setText("sqrt");
        sqrtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtButtonActionPerformed(evt);
            }
        });

        percentageButton.setBackground(new java.awt.Color(255, 255, 255));
        percentageButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        percentageButton.setText("%");
        percentageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentageButtonActionPerformed(evt);
            }
        });

        x2Button.setBackground(new java.awt.Color(204, 255, 255));
        x2Button.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        x2Button.setText("x2");
        x2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x2ButtonActionPerformed(evt);
            }
        });

        cButton.setBackground(new java.awt.Color(153, 255, 255));
        cButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cButton.setText("C");
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        onOffButton.setBackground(new java.awt.Color(255, 102, 102));
        onOffButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        onOffButton.setForeground(new java.awt.Color(204, 0, 0));
        onOffButton.setText("ON/OFF");
        onOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOffButtonActionPerformed(evt);
            }
        });

        backspaceButton.setBackground(new java.awt.Color(204, 255, 255));
        backspaceButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        backspaceButton.setText("<--");
        backspaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceButtonActionPerformed(evt);
            }
        });

        oneByXButton.setBackground(new java.awt.Color(204, 255, 255));
        oneByXButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        oneByXButton.setText("1/x");
        oneByXButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneByXButtonActionPerformed(evt);
            }
        });

        divideButton.setBackground(new java.awt.Color(255, 255, 255));
        divideButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        divideButton.setText("/");
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });

        oneButton.setBackground(new java.awt.Color(204, 255, 0));
        oneButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        oneButton.setText("1");
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });

        twoButton.setBackground(new java.awt.Color(204, 255, 0));
        twoButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        twoButton.setText("2");
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonActionPerformed(evt);
            }
        });

        threeButton.setBackground(new java.awt.Color(204, 255, 0));
        threeButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        threeButton.setText("3");
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonActionPerformed(evt);
            }
        });

        minusButton.setBackground(new java.awt.Color(204, 255, 255));
        minusButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        minusButton.setText("-");
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });

        sixButton.setBackground(new java.awt.Color(204, 255, 0));
        sixButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        sixButton.setText("6");
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonActionPerformed(evt);
            }
        });

        fiveButton.setBackground(new java.awt.Color(204, 255, 0));
        fiveButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        fiveButton.setText("5");
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonActionPerformed(evt);
            }
        });

        fourButton.setBackground(new java.awt.Color(204, 255, 0));
        fourButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        fourButton.setText("4");
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonActionPerformed(evt);
            }
        });

        sevenButton.setBackground(new java.awt.Color(204, 255, 0));
        sevenButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        sevenButton.setText("7");
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonActionPerformed(evt);
            }
        });

        eightButton.setBackground(new java.awt.Color(204, 255, 0));
        eightButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        eightButton.setText("8");
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonActionPerformed(evt);
            }
        });

        nineButton.setBackground(new java.awt.Color(204, 255, 0));
        nineButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        nineButton.setText("9");
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonActionPerformed(evt);
            }
        });

        multiplyButton.setBackground(new java.awt.Color(204, 255, 255));
        multiplyButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        multiplyButton.setText("*");
        multiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonActionPerformed(evt);
            }
        });

        plusButton.setBackground(new java.awt.Color(204, 255, 0));
        plusButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        plusButton.setText("+");
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        zeroButton.setBackground(new java.awt.Color(204, 255, 0));
        zeroButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        zeroButton.setText("0");
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });

        dotButton.setBackground(new java.awt.Color(204, 255, 0));
        dotButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        dotButton.setText(".");
        dotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotButtonActionPerformed(evt);
            }
        });

        equalButton.setBackground(new java.awt.Color(204, 255, 255));
        equalButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        equalButton.setText("=");
        equalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalButtonActionPerformed(evt);
            }
        });

        outputScreen.setEditable(false);
        outputScreen.setBackground(new java.awt.Color(255, 255, 204));
        outputScreen.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 30)); // NOI18N
        outputScreen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        outputScreen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        outputScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputScreenActionPerformed(evt);
            }
        });

        labelScreen.setBackground(new java.awt.Color(0, 153, 153));
        labelScreen.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        labelScreen.setForeground(new java.awt.Color(51, 255, 0));
        labelScreen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(multiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(equalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addComponent(outputScreen, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(x2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(oneByXButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(percentageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sqrtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(onOffButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(labelScreen)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(outputScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentageButton)
                    .addComponent(sqrtButton)
                    .addComponent(onOffButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cButton)
                    .addComponent(x2Button)
                    .addComponent(backspaceButton)
                    .addComponent(oneByXButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(divideButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(sevenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fourButton)
                    .addComponent(fiveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sixButton)
                        .addComponent(multiplyButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneButton)
                    .addComponent(twoButton)
                    .addComponent(threeButton)
                    .addComponent(minusButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plusButton)
                    .addComponent(zeroButton)
                    .addComponent(dotButton)
                    .addComponent(equalButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sqrtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtButtonActionPerformed
        // TODO add your handling code here:
        if(outputScreen.getText().length()>0)
        {
        toBeCalculated = Double.parseDouble((outputScreen.getText()));
        sqrt(toBeCalculated);
        }
    }//GEN-LAST:event_sqrtButtonActionPerformed

    private void sqrt(double a)
    {
      outputScreen.setText(Double.toString(Math.sqrt(a)));
    }
    private void percentageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentageButtonActionPerformed
       
        if(outputScreen.getText().length()>0 && labelScreen.getText().length()>0)
        {
             toBeCalculated = Double.parseDouble((outputScreen.getText()));
             percentage(Double.parseDouble(labelScreen.getText().split(" ")[0]),toBeCalculated);
        }
            // TODO add your handling code here:
          //   outputScreen.setText(outputScreen.getText()+"%");
    }//GEN-LAST:event_percentageButtonActionPerformed
   private void percentage(double a, double b)
   {
        switch(sign)
        {
            case "+":
                plus(((a*b)/100),a);
                break;
            case "-":
                minus(((a*b)/100),a);
                break;
            case "*":
                multiplication(((a*b)/100),a);
                break;
            case "/":
                division(((a*b)/100),a);
                break;
        }
   }
    private void x2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2ButtonActionPerformed
        // TODO add your handling code here:
        if(outputScreen.getText().length()>0)
        {
            outputScreen.setText(Double.toString((Double.parseDouble((outputScreen.getText())))*(Double.parseDouble((outputScreen.getText())))));
        }
    }//GEN-LAST:event_x2ButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        // TODO add your handling code here:
        outputScreen.setText("");
        labelScreen.setText("");
        isDecimal=false;
    }//GEN-LAST:event_cButtonActionPerformed

    private void onOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOffButtonActionPerformed
        // TODO add your handling code here:
        if(check==0)    
        {disable1();
        outputScreen.setText("");
        labelScreen.setText("");
        
        check=1;
        }
        else
        {
            enable1();
            check=0;
        }
    }//GEN-LAST:event_onOffButtonActionPerformed

    private void backspaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceButtonActionPerformed

        // TODO add your handling code here:
        String value = outputScreen.getText();
        int length = value.length();
        
        if(length>0)
        {
            StringBuilder builder = new StringBuilder(value);
            builder.deleteCharAt(length-1);
            outputScreen.setText(builder.toString());
        }
    }//GEN-LAST:event_backspaceButtonActionPerformed

    private void oneByXButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneByXButtonActionPerformed
        // TODO add your handling code here:
        if(outputScreen.getText().length()>0)
        {
             outputScreen.setText(Double.toString(1/Double.parseDouble((outputScreen.getText()))));
        }
    }//GEN-LAST:event_oneByXButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
        // TODO add your handling code here:
        temp=0;
       sign = "/";
         if(outputScreen.getText().length()>0)
          storeToBeCalculatedValue(sign);
                 isDecimal=false;
          
        // outputScreen.setText(outputScreen.getText()+"/");
    }//GEN-LAST:event_divideButtonActionPerformed

    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonActionPerformed
        // TODO add your handling code here:
             outputScreen.setText(outputScreen.getText()+"1");
    }//GEN-LAST:event_oneButtonActionPerformed

    private void twoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonActionPerformed
        // TODO add your handling code here:
             outputScreen.setText(outputScreen.getText()+"2");
    }//GEN-LAST:event_twoButtonActionPerformed

    private void threeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonActionPerformed
        // TODO add your handling code here:
             outputScreen.setText(outputScreen.getText()+"3");
    }//GEN-LAST:event_threeButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
temp=0;
isDecimal=false;             // TODO add your handling code here:
        sign = "-";
         if(outputScreen.getText().length()>0)
            storeToBeCalculatedValue(sign);
           //  outputScreen.setText(outputScreen.getText()+"-");
    }//GEN-LAST:event_minusButtonActionPerformed

    private void sixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonActionPerformed
        // TODO add your handling code here:
             outputScreen.setText(outputScreen.getText()+"6");
    }//GEN-LAST:event_sixButtonActionPerformed

    private void fiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonActionPerformed
        // TODO add your handling code here:
             outputScreen.setText(outputScreen.getText()+"5");
    }//GEN-LAST:event_fiveButtonActionPerformed

    private void fourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonActionPerformed
        // TODO add your handling code here:
             outputScreen.setText(outputScreen.getText()+"4");
    }//GEN-LAST:event_fourButtonActionPerformed

    private void sevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonActionPerformed
        // TODO add your handling code here:
             outputScreen.setText(outputScreen.getText()+"7");
    }//GEN-LAST:event_sevenButtonActionPerformed

    private void eightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonActionPerformed
        // TODO add your handling code here:
             outputScreen.setText(outputScreen.getText()+"8");
    }//GEN-LAST:event_eightButtonActionPerformed

    private void nineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonActionPerformed
        // TODO add your handling code here:
             outputScreen.setText(outputScreen.getText()+"9");
    }//GEN-LAST:event_nineButtonActionPerformed

    private void multiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButtonActionPerformed
temp=0;        
         sign = "*";
         if(outputScreen.getText().length()>0)
          storeToBeCalculatedValue(sign);  
                 isDecimal=false;// TODO add your handling code here:
       
           //  outputScreen.setText(outputScreen.getText()+"*");
    }//GEN-LAST:event_multiplyButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
temp=0;
        isDecimal=false;
        sign = "+";
        if(outputScreen.getText().length()>0)
          storeToBeCalculatedValue(sign);
        //outputScreen.setText(outputScreen.getText()+"+");
    // TODO add your handling code here:
   
    }//GEN-LAST:event_plusButtonActionPerformed

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed

        // TODO add your handling code here:
        outputScreen.setText(outputScreen.getText()+"0");
    }//GEN-LAST:event_zeroButtonActionPerformed

    private void dotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotButtonActionPerformed
        // TODO add your handling code here:
        if(!isDecimal)
        {
             outputScreen.setText(outputScreen.getText()+".");
             isDecimal = true;
        }
    }//GEN-LAST:event_dotButtonActionPerformed

    private void equalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalButtonActionPerformed
        // TODO add your handling code here:
             //outputScreen.setText("");
             if(outputScreen.getText().length()>0 && temp==0)
             {
             double b = Double.parseDouble(outputScreen.getText());
             switch(sign)
             {
                 case "+":
                     plus(toBeCalculated,b);
                     break;
                 case "-":
                     minus(toBeCalculated,b);
                     break;
                 case "*":
                     multiplication(toBeCalculated,b);
                     break;
                 case "/":
                     division(toBeCalculated,b);
                     break;
                 default:
                     outputScreen.setText("0.0");
             
             }           
             temp=1;
             }
             else
                 outputScreen.setText(outputScreen.getText());
             //isDecimal=true;
    }//GEN-LAST:event_equalButtonActionPerformed

    
    private void outputScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputScreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputScreenActionPerformed

    /**
     * @param args the command line arguments
     */
    private void storeToBeCalculatedValue(String sign)
    {
        String value = outputScreen.getText();
        toBeCalculated = Double.parseDouble(value);
        labelScreen.setText(value+" "+sign);
        outputScreen.setText("");
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }
    private int check=0;
    private int temp =0;
    private String sign;
    private boolean isDecimal= false;
    private double toBeCalculated;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backspaceButton;
    private javax.swing.JButton cButton;
    private javax.swing.JButton divideButton;
    private javax.swing.JButton dotButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JTextField labelScreen;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton onOffButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton oneByXButton;
    private javax.swing.JTextField outputScreen;
    private javax.swing.JButton percentageButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton sqrtButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton x2Button;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void plus(double a, double b) {
        setResult(a+b);
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void minus(double a, double b) {
        setResult(a-b);
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void multiplication(double a, double b) {
        setResult(a*b);
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void division(double a, double b) {
        setResult(a/b);
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void setResult(double result){
        outputScreen.setText(Double.toString(result));
        labelScreen.setText("");
    }
}
